#!/bin/bash

set -e
IFS="
"

SERENITY_MASTER=${SERENITY_MASTER:-serenity_master}
SERENITY_FORK=${SERENITY_FORK:-serenity_fork}

branch_id=""

if [ $# = 1 ]; then
  branch_id="pr_$1"
else
  branch_id="bulk_sync_$(date +%s)"
fi

pr_title=""
body=""

git checkout $SERENITY_MASTER
git checkout -B $branch_id

for pr_number in $@; do
  body="${body}Cherry-picks LadybirdBrowser/ladybird#$pr_number<br>"

  pr=$(gh pr view $pr_number --json title,commits)
  pr_title=$(jq -r ".title" <<< "$pr")
  pr_commits=$(jq -r ".commits[].messageHeadline" <<< "$pr")

  commit_hashes=""

  for commit in $pr_commits; do
    hash=$(gh search commits --repo "LadybirdBrowser/ladybird" "$commit" --json sha | jq -r ".[0].sha")
    echo "Found commit $hash"
    
    commit_hashes="$commit_hashes
$hash"
  done

  for hash in $commit_hashes; do
    if ! git cherry-pick -x $hash; then
      read -p "You may now fix the cherry-pick error. Continue? y/n " yn
      if [ $yn != "y" ]; then
        git cherry-pick --abort || true
        git checkout $SERENITY_MASTER
        git branch -D $branch_id
        exit
      fi
    fi
  done
done

title=""

if [ $# = 1 ]; then
  title="Cherry-pick \"$pr_title\""
else
  title="Cherry-pick $# PRs from Ladybird"
fi

read -p "You may edit the commits now. Create PR? y/n " yn

if [ $yn = "y" ]; then
  git push --set-upstream $SERENITY_FORK $branch_id
  gh pr create --repo "SerenityOS/serenity" --title "$title" --body "$body<sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>"
fi
